### PR TITLE
Implemented getting latest SCA results for a specific project

### PR DESCRIPTION
**Pull request by alex-ko-dev**
### Description

Implemented the AstScaClient.getLatestScanResults() method. The method only contained a stub previously.
The target project is determined by name (CxScanConfig.getProjectName). Latest scan results can be obtained from ScanResults.getScaResults property. 

Latest scan results will be null in the following cases:
- target project doesn't exist
- target project has no scans
- none of the project scans is successful

The **AstScaSummaryResults.riskReportId** was removed, because this is now the same thing as AstScaResults.scanId (after changes on the SCA side).

### References

Work item [219](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/219/).

### Testing

Added relevant integration tests to AstScaTests.

### CODE REVIEW

**Comment by ghannamz** [comment]
Scan submitted to Checkmarx

**Comment by ghannamz** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010761&projectid=238)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|11
Low|146
Informational|2

#### Violation Summary
Severity|Count
---|---
Medium|11

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[10](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/ProxyConfig.java#L10) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/ProxyConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010761&projectid=238&pathid=6)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010761&projectid=238&pathid=4)
[16](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java#L16) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010761&projectid=238&pathid=7)
[14](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginSettings.java#L14) [22](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginSettings.java#L22) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginSettings.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010761&projectid=238&pathid=5)
[21](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java#L21) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010761&projectid=238&pathid=9)
[120](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/ast/AstClient.java#L120) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010761&projectid=238&pathid=1)
[113](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/ast/AstScaClient.java#L113) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstScaClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010761&projectid=238&pathid=2)
[31](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L31) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010761&projectid=238&pathid=3)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/osa/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010761&projectid=238&pathid=8)
[233](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L233) |Medium|Privacy_Violation|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010761&projectid=238&pathid=159)

**Comment by ghannamz** [comment]
Scan submitted to Checkmarx

**Comment by ghannamz** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010768&projectid=238)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|11
Low|146
Informational|2

#### Violation Summary
Severity|Count
---|---
Medium|11

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[10](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/ProxyConfig.java#L10) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/ProxyConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010768&projectid=238&pathid=61)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010768&projectid=238&pathid=59)
[16](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java#L16) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010768&projectid=238&pathid=62)
[14](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginSettings.java#L14) [22](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginSettings.java#L22) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginSettings.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010768&projectid=238&pathid=60)
[21](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java#L21) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010768&projectid=238&pathid=64)
[120](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/ast/AstClient.java#L120) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010768&projectid=238&pathid=56)
[113](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/ast/AstScaClient.java#L113) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstScaClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010768&projectid=238&pathid=57)
[31](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L31) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010768&projectid=238&pathid=58)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/osa/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010768&projectid=238&pathid=63)
[233](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L233) |Medium|Privacy_Violation|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010768&projectid=238&pathid=159)

**Comment by ghannamz** [comment]
Scan submitted to Checkmarx

**Comment by ghannamz** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|13
Low|163
Informational|2

#### Violation Summary
Severity|Count
---|---
Medium|12

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[10](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/ProxyConfig.java#L10) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/ProxyConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238&pathid=65)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238&pathid=63)
[16](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java#L16) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238&pathid=66)
[14](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginSettings.java#L14) [22](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginSettings.java#L22) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginSettings.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238&pathid=64)
[21](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java#L21) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238&pathid=68)
[121](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/ast/AstClient.java#L121) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238&pathid=60)
[135](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/ast/AstScaClient.java#L135) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstScaClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238&pathid=61)
[31](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L31) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238&pathid=62)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/osa/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238&pathid=67)
[233](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L233) |Medium|Privacy_Violation|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238&pathid=178)
[40](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/sca/utils/fingerprints/FingerprintCollector.java#L40) |Medium|Use_of_a_One_Way_Hash_with_a_Predictable_Salt|src/main/java/com/cx/restclient/sca/utils/fingerprints/FingerprintCollector.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010771&projectid=238&pathid=8)

**Comment by ghannamz** [comment]
Scan submitted to Checkmarx

**Comment by ghannamz** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|13
Low|163
Informational|2

#### Violation Summary
Severity|Count
---|---
Medium|12

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[10](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/ProxyConfig.java#L10) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/ProxyConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238&pathid=65)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238&pathid=63)
[16](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java#L16) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238&pathid=66)
[14](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginSettings.java#L14) [22](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/dto/LoginSettings.java#L22) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginSettings.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238&pathid=64)
[21](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java#L21) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238&pathid=68)
[121](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/ast/AstClient.java#L121) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238&pathid=60)
[129](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/ast/AstScaClient.java#L129) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstScaClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238&pathid=61)
[31](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L31) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238&pathid=62)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/osa/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238&pathid=67)
[233](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L233) |Medium|Privacy_Violation|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238&pathid=178)
[40](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/alexey-219-getting-latest-sca-results/src/main/java/com/cx/restclient/sca/utils/fingerprints/FingerprintCollector.java#L40) |Medium|Use_of_a_One_Way_Hash_with_a_Predictable_Salt|src/main/java/com/cx/restclient/sca/utils/fingerprints/FingerprintCollector.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010772&projectid=238&pathid=8)

**Review by AvivCX — APPROVED** [review]

**Pull request merged**
