### PR TITLE
Add unit tests to mvn tests

### PR DESCRIPTION
**Pull request by zakashe**
By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ltd/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Some UTs are implemented in the source code, but not executed in pipeline

### Testing

>I used "mvn test" to test my PR

### CODE REVIEW

**Comment by ghannamz** [comment]
Scan submitted to Checkmarx

**Comment by ghannamz** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010751&projectid=236)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|11
Low|146
Informational|2

#### Violation Summary
Severity|Count
---|---
Medium|11

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[120](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/ast/AstClient.java#L120) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010751&projectid=236&pathid=56)
[16](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java#L16) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010751&projectid=236&pathid=62)
[10](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/dto/ProxyConfig.java#L10) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/ProxyConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010751&projectid=236&pathid=61)
[31](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L31) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010751&projectid=236&pathid=58)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010751&projectid=236&pathid=59)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/osa/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010751&projectid=236&pathid=63)
[14](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/dto/LoginSettings.java#L14) [22](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/dto/LoginSettings.java#L22) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginSettings.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010751&projectid=236&pathid=60)
[120](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/ast/AstScaClient.java#L120) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstScaClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010751&projectid=236&pathid=57)
[21](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java#L21) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010751&projectid=236&pathid=64)
[233](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L233) |Medium|Privacy_Violation|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010751&projectid=236&pathid=159)

**Comment by ghannamz** [comment]
Scan submitted to Checkmarx

**Comment by ghannamz** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010752&projectid=236)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|11
Low|146
Informational|2

#### Violation Summary
Severity|Count
---|---
Medium|11

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[120](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/ast/AstClient.java#L120) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010752&projectid=236&pathid=56)
[16](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java#L16) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/RemoteSourceRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010752&projectid=236&pathid=62)
[10](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/dto/ProxyConfig.java#L10) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/ProxyConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010752&projectid=236&pathid=61)
[31](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L31) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010752&projectid=236&pathid=58)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010752&projectid=236&pathid=59)
[13](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/osa/dto/LoginRequest.java#L13) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/LoginRequest.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010752&projectid=236&pathid=63)
[14](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/dto/LoginSettings.java#L14) [22](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/dto/LoginSettings.java#L22) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/dto/LoginSettings.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010752&projectid=236&pathid=60)
[120](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/ast/AstScaClient.java#L120) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/ast/AstScaClient.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010752&projectid=236&pathid=57)
[21](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java#L21) |Medium|Heap_Inspection|src/main/java/com/cx/restclient/osa/dto/ScanConfiguration.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010752&projectid=236&pathid=64)
[233](https://github.com/checkmarx-ltd/Cx-Client-Common/blob/fix-unit-tests/src/main/java/com/cx/restclient/configuration/CxScanConfig.java#L233) |Medium|Privacy_Violation|src/main/java/com/cx/restclient/configuration/CxScanConfig.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010752&projectid=236&pathid=159)

**Comment by zakashe** [comment]
@ghannamz @cx-muhammed @olgakil @alex-ko-dev Could you please review?

**Review by alex-ko-dev — COMMENTED** [review]
com.cx.restclient.configuration.CxScanConfigTest#getSetSastEnabled: assertions can be simplified to assertTrue/assertFalse.

com.cx.restclient.configuration.CxScanConfigTest#getSetCxOrigin - 'expected' and 'actual' arguments should be reversed in assertEquals.

I doubt whether we need CxScanConfigTest at all. It's a legacy test that just checks if getters and setters work for a certain DTO. It just creates additional noise.

**Comment by zakashe** [comment]
Hi @alex-ko-dev ,
I totally agree with you.
Nonetheless, I did not want to dive into massive refactoring.
Personally I think that dto such as CxScanConfig should not have setters and getters but public members (except to maybe collections).

Initially there were bunch of tests that did not run, the reason they didn't run were wrong name (ending with Tests instead of test) I wanted to fix that only.

There are lot of things I'd do differently (e.g. separate many tests) but didn't want to complex this specific PR.

**Comment by alex-ko-dev** [comment]
Hi @ghannamz , are you familiar with the CI error that occurred in this PR? This looks like an infrastructure issue.

[2020-08-18T13:56:54.441Z] # There is insufficient memory for the Java Runtime Environment to continue.

**Review by alex-ko-dev — APPROVED** [review]

**Comment by alex-ko-dev** [comment]
The problem with @Ignore is that we use these tests to check functionality locally. So we'll need to remove @Ignore for each test that needs to be run and make sure this change is not committed.

**Pull request merged**
